// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novia.Guestbook.Infrastructure.Data.Ef;

namespace Novia.Guestbook.Infrastructure.Data.Ef.Migrations
{
    [DbContext(typeof(GuestbookDbContext))]
    partial class GuestbookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Novia.Guestbook.Domain.Entities.Guestbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Guestbooks");
                });

            modelBuilder.Entity("Novia.Guestbook.Domain.Entities.GuestbookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BelongsToId");

                    b.Property<DateTimeOffset>("DateTimeCreated");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("Message");

                    b.HasKey("Id");

                    b.HasIndex("BelongsToId");

                    b.ToTable("GuestbookEntries");
                });

            modelBuilder.Entity("Novia.Guestbook.Domain.Entities.GuestbookEntry", b =>
                {
                    b.HasOne("Novia.Guestbook.Domain.Entities.Guestbook", "BelongsTo")
                        .WithMany("Entries")
                        .HasForeignKey("BelongsToId");
                });
#pragma warning restore 612, 618
        }
    }
}
